---
title: "Collaborator Analysis"
format: html
author: "Natalia Varela"
---
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

## Exercise: Explore, Clean, and Wrangle Data

```{r}
# reading data file
lobster_traps <- read_csv("../data/Lobster_Trap_Counts_All_Years_20210519.csv")
```
# Question 1: convert missing values using mutate () and na_if()
```{r}
lobster_traps <- lobster_traps %>% 
  mutate(TRAPS = na_if(TRAPS, -99999))

#To check if the output changed
unique(lobster_traps$TRAPS)
```

# Question 2: filter ( ) practice
```{r}
lobster_traps_not_NAPL <- lobster_traps %>% 
  filter(SITE != "NAPL")
```

# Question 3: filter ( ) practice

```{r}
carp_reef_traps <- lobster_traps %>% 
  filter(SITE == "CARP" &  TRAPS > 20)
```

# Question 4: filter ( ) practice

```{r}
summarize(TRAPS = max())

max_comm_trap  <- lobster_traps %>% 
  group_by(SITE,MONTH) %>% 
  summarize(count(TRAPS) = max(TRAPS, na.rm = TRUE))

```

## Exercise: Data Visualization

# Question 5: ggplot- multipanel

```{r}
Q5   <- ggplot(lobster_traps, aes(x = TRAPS))+
  geom_histogram()+
  facet_wrap(~YEAR)

Q5
```
# Question 6: Create a line graph of the number of total lobster commercial traps observed (y-axis) by year (x-axis)

```{r}
lobsters_traps_summ<- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE)) #the "sum" function goes in summarize

Q6_line_plot <- ggplot(lobsters_traps_summ, aes(x = YEAR, y = TOTAL_TRAPS))+
  geom_line()
Q6_line_plot
```

